server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=utf-8&autoReconnectForPools=true&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 5MB
  liquibase:
    change-log: classpath:/change/changelog-master.xml
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 115.29.179.157:9300

mybatis:
  type-aliases-package: com.lin.shopping.item.pojo
  mapper-locations: classpath*:/mybatis/*/*.xml,classpath*:/mybatis/*.xml

fdfs:
  so-timeout: 1501 #超时时间
  connect-timeout: 601 #连接超时时间
  thumb-image:  #缩略图
    width: 60
    height: 60
  tracker-list: #tracker地址
    - 115.29.179.157:22122


